ci:
  autofix_prs: false
  autoupdate_schedule: weekly
  autoupdate_commit_msg: 'chore: pre-commit autoupdate'

repos:
- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort

- repo: https://github.com/pycqa/flake8
  rev: 5.0.2
  hooks:
  - id: flake8
    additional_dependencies:
    - darglint==1.8.1
    - flake8-docstrings==1.6.0