[tool.poetry]
name = "ext-airflow"
version = "0.1.0"
description = "Airflow utility extension for Meltano"
authors = ["Meltano Team and Contributors"]
maintainers = ["Meltano Team and Contributors"]
readme = "README.md"
repository = "https://github.com/meltano/ext-airflow"

license = "Apache 2.0"

packages = [
    { include = "ext_airflow" },
    { include = "files_airflow_ext"},
    { include = "meltano_extension_sdk" }
]

include = [
    "files_airflow_ext/orchestrate/meltano.py",
    "files_airflow_ext/orchestrate/README.md",
]

[tool.poetry.dependencies]
python = "^3.8"
structlog = "^21.2.0"
PyYAML = "^6.0.0"
pydantic = "^1.9.0"
typer = "^0.6.1"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
isort = "^5.10.1"
flake8 = "^3.9.0"
cookiecutter = "^2.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
airflow_extension = 'ext_airflow.main:app'
airflow_invoker = 'ext_airflow.pass_through:pass_through_cli'
