name: Test

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  test:
    name: Test (${{ matrix.tox-env }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tox-env:
          - py310-airflow2
          - py311-airflow2
          - py312-airflow2
          - py310-airflow3
          - py311-airflow3
          - py312-airflow3
          - py313-airflow3
          - py314-airflow3
    steps:
      - name: Check out repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
        with:
          enable-cache: true

      - name: Run tests
        env:
          TOXENV: ${{ matrix.tox-env }}
        run: uv run tox
